spring:
  profiles:
    active: dev
---
server:
  port: 4011
spring:
  profiles: dev
  application:
    name: microservice-config-dev
---
server:
  port: 4012
spring:
  profiles: prod
  application:
    name: microservice-config-prod