emp:
  name: zhangsam
spring:
  profiles:
    active: dev
---
server:
  port: 8001

spring:
  profiles: dev
  application:
    name: microservice-product-config-dev-bus

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka6001.com:6001/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${server.port}-dev
    prefer-ip-address: true
---
server:
  port: 8011

spring:
  profiles: prod
  application:
    name: microservice-product-config-prod

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka6001.com:6001/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${server.port}-prod
    prefer-ip-address: true
